apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q86kyciy6-go 
  janus-idp.io/tekton: q86kyciy6-go
  backstage.io/kubernetes-id: q86kyciy6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q86kyciy6-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml